### ISSUE TITLE
Unable to link Brand to Product

### ISSUE THREAD

**Issue by AxelDeneu** [loevgaard/SyliusBrandPlugin#37]
Sylius brand plugin version : `1.3.2`
Sylius version : `1.4.0`
PHP version : `7.2.15`

I'm probably dumb but since I've installed the SyliusBrandPlugin, I'm unable to make it work...
I've followed all the steps on the README. But when I try to link a Brand to a Product via the admin dashboard. The modification is done but not effective (the brand remains not linked).
I've checked in the database and the brand table is successfully created because I can create a brand.

However, there isn't any brandId or brand property in the product table. That's probably why it does not work fo me. And when I run a schema update, Doctrine says that the database is up to date.

I tried to figure out what's going on and I found this error in the Symfony logs : 

> The association Loevgaard\SyliusBrandPlugin\Entity\Brand#products refers to the owning side field App\Entity\Product\Product#brand which does not exist.

Please help me <3

**Comment by loevgaard** [comment]
Hi @AxelDeneu 

We are developing v2 of this plugin *right* now. So if you can wait a week a new version will be available :)

**Comment by AxelDeneu** [comment]
Hi @loevgaard 
Thank you for your answer! I'll wait and give you feedback :)

**Comment by loevgaard** [comment]
We just released the beta, so please install that and give us feedback as soon as you can :) 

https://github.com/loevgaard/SyliusBrandPlugin/releases/tag/v2.0.0-beta

**Comment by AxelDeneu** [comment]
Great!
I'll check this out tonight :)

**Comment by igormukhingmailcom** [comment]
I guess this is because there was no instructions to add doctrine mapping for Product at `README.md`. 

Now it there, btw.

**Comment by AxelDeneu** [comment]
Thank you @igormukhingmailcom ! I'll check this out!

**Comment by AxelDeneu** [comment]
Hey @igormukhingmailcom,
I followed your instructions but I'm still unable to make it work. I use annotation for doctrine mapping. So I can't switch to yml for doctrine mapping without blowing my project up.
Do you know which annotations do I need to specify to make it work ?

**Comment by igormukhingmailcom** [comment]
@AxelDeneu Yeah, we already know about this issue.
Today evening should be update with annotations for trait which should work on default Sylius configuration.

**Comment by AxelDeneu** [comment]
Nice! Thank you @igormukhingmailcom

**Comment by igormukhingmailcom** [comment]
@AxelDeneu , please see updated instructions.

Related: https://github.com/loevgaard/SyliusBrandPlugin/issues/43

**Comment by AxelDeneu** [comment]
Thank you for your great work guys!
Unfortunally, a new error appeared. I probably miss something but Symfony keep showing me this error : 
```
ParameterNotFoundException
You have requested a non-existent parameter "loevgaard_sylius_brand.model.brand.class".
```

**Comment by AxelDeneu** [comment]
Everything work like a charm!
I've been blind enough to not see the `@ORM\Entity` in the README. By default, this line is with the value `@ORM\MappedSuperclass`.
Could it be interesting to add a comment above saying that this line mandatory ? (because without it, the foreign key isn't created in the product table).

Thank you for the great work @loevgaard and @igormukhingmailcom !

**Comment by loevgaard** [comment]
You're very welcome :)

**Comment by hous04** [comment]
Hi
in 2023 I had the same error:

> You have requested a non-existent parameter "loevgaard_sylius_brand.model.brand.class"

![Capture d’écran du 2023-08-02 18-31-44](https://github.com/loevgaard/SyliusBrandPlugin/assets/24528261/1e03c0c5-5dbe-45b3-858b-9319bb48d889)
